baseURL = "https://sketches.hardikp.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Hardik's Sketches"
enableRobotsTXT = true
enableEmoji = true
theme = "even"
publishDir = "docs"
RSSLink = "https://sketches.hardikp.com/index.xml"
canonifyurls = false

paginate = 1
googleAnalytics = "UA-79877480-2"

[author]                  # essential
  name = "Hardik Patel"
  email = "hi@hardikp.com"

[social]
  twitter = "hardikp"

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 30             # weight = 20 is used by "About" page
  identifier = "archive"
  url = "/post/"
[[menu.main]]
  name = "Twitter"
  weight = 40
  identifier = "twitter"
  url = "https://twitter.com/hardikp"

[mediaTypes]
  [mediaTypes."application/atom"]
    suffix = "xml"

[outputFormats.Atom]
  mediaType = "application/atom"
  baseName = "index"
  isPlainText = false

[outputs]
  home = [ "HTML", "Atom" ]

[params]
  version = "3.x"           # Used to give a friendly message when you have an incompatible update

  since = "2018"            # Site creation time

  # site info (optional)
  logoTitle = ""        # default: the title value
  keywords = ["comics", "sketches", "comic", "sketch", "webcomic", "hardik", "hardik patel"]
  description = "Hardik's short comics and sketches"

  # paginate of archives, tags and categories
  archivePaginate = 5

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?
  moreMeta = false

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true
  autoCollapseToc = false   # Auto expand and collapse toc
  fancybox = true           # see https://github.com/fancyapps/fancybox
  mathjax = false           # see https://www.mathjax.org/
  mathjaxEnableSingleDollar = false

  postMetaInFooter = true   # contain author, lastMod, markdown link, license
  linkToMarkDown = false    # Only effective when hugo will output .md files.
  contentCopyright = ''     # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  [params.social]
    a-email = "mailto:hardikp12@gmail.com"
    c-twitter = "https://twitter.com/hardikp"
    e-linkedin = "https://www.linkedin.com/in/hardikp12/"
    g-github = "https://github.com/hardikp/sketches"
    m-instagram = "https://www.instagram.com/hardikp/"
